### PR TITLE
Introduce Myself / added to contributors data

### PR DESCRIPTION
**Pull request by ArchismanKarmakar**
#6 introduced

### 3. *Form 3(Introduction)*

<br>

# 1) Form 1
### Issue Id - 
Mention your issue ID here

<br>

### Topic you have been working upon
Write your answer here

<br>

### One screenshot of the document
Write your answer here

# 2) Form 2
### Issue Id - 
Mention your issue ID here

<br>

### Screenshot of the line where you found the bug
Write your answer here

# 3) Form 3
### Issue ID - 
Mention your issue ID here

### CODE REVIEW

**Comment by rohitkumar9710** [comment]
@ArchismanKarmakar 
Kindly remove your details from `mentors.json`. Only `participants.json` is meant to be filled.

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar 
> Kindly remove your details from `mentors.json`. Only `participants.json` is meant to be filled.

Sir, I am participating as well as I have given my own project called Hotel Website, you can check CODEPEAK website, then why?

**Comment by rohitkumar9710** [comment]
@ArchismanKarmakar 
Here, mentors refer to the mentors for just this repository. And the issue asks you to fill only the `participants.json`, so.

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar Here, mentors refer to the mentors for just this repository. And the issue asks you to fill only the `participants.json`, so.

okay i've changed it

**Pull request merged**
